services:
  database:
    image: postgres:15-alpine
    container_name: sgv-postgres
    environment:
      # O Docker puxa os valores do seu arquivo .env automaticamente
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sgv_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Isso faz o Docker rodar o script de criação de usuários na primeira inicialização
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sgv_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - sgv-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sgv-backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/sgv_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpassword
    ports:
      - "8080:8080"
    networks:
      - sgv-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sgv-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - sgv-network

volumes:
  pgdata:

networks:
  sgv-network:
    driver: bridge
